export const STUDENTS_LIST_REQUEST = 'STUDENTS_LIST_REQUEST'
export const STUDENTS_LIST_SUCCESS = 'STUDENTS_LIST_SUCCESS'
export const STUDENTS_LIST_FAIL = 'STUDENTS_LIST_FAIL'

export const STUDENT_DETAIL_REQUEST = 'STUDENT_DETAIL_REQUEST'
export const STUDENT_DETAIL_SUCCESS = 'STUDENT_DETAIL_SUCCESS'
export const STUDENT_DETAIL_FAIL = 'STUDENT_DETAIL_FAIL'
